### ISSUE TITLE
Awesome Analysis - Small Suggestions

### ISSUE THREAD

**Issue by d-wasserman** [kellytdunn/Seattle-parks#1]
Awesome analysis. I think my only feedback is it is a good practice to [declare the time-zone](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.tz_convert.html) for  analysis in your datetime. Given the use patterns, this does not seem to be a problem here, but it could be if you use more global datasets with datetimes in UTC for example. Getting everything into the same time-zone is like projection matching for geospatial analysis. That said, a lot of us do work with "[naïve](https://docs.python.org/3/library/datetime.html)" datetimes all the time. 
Also the performance at lower temperatures might not be an anomaly. People might use the parks more if it snows (which is what the poly model might be capturing, but it is hard to tell). That is something I would be curious about though.

**Comment by kellytdunn** [comment]
Thanks @d-wasserman ! I will add this to my backlog.
